trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md
    - azure-pipeline.png

variables:
  vmImage: 'ubuntu-16.04'
  terraformVersion: 0.12.14
  tfFilesArtifactName: 'tf-files'

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Prepare'
    displayName: 'Prepare'
    pool:
      vmImage: $(vmImage)
    steps:
    - publish: '$(system.defaultWorkingDirectory)/tf'
      artifact: $(tfFilesArtifactName)
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)
    - script: |
        terraform init \
            -backend=false
        terraform validate
      workingDirectory: $(system.defaultWorkingDirectory)/tf
      displayName: 'Terraform validate'
- stage: 'Plan_development'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: 'Plan development'
  variables:
    - group: tf-sp-group-dev
    - group: tf-state-group-dev
    - group: tf-deployment-group-dev
  jobs:
  - job: 'Plan'
    displayName: 'Plan'
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - download: current
      artifact: $(tfFilesArtifactName)
    - script: |
        terraform init \
            -backend-config="storage_account_name=$(tfStateStorageAccountName)" \
            -backend-config="container_name=$(tfStateStorageContainerName)"
        terraform plan \
            -var resource_group_name=$(resourceGroupName) \
            -var location=$(location)
      workingDirectory: $(pipeline.workspace)/$(tfFilesArtifactName)
      displayName: 'Terraform plan'
      env:
          ARM_TENANT_ID: $(tenantId)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
- stage: 'Apply_development'
  displayName: 'Apply development'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  variables:
    - group: tf-sp-group-dev
    - group: tf-state-group-dev
    - group: tf-deployment-group-dev
  jobs:
  - deployment: 'Apply'
    displayName: 'Apply'
    pool:
      vmImage: $(vmImage)
    environment: tf-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - download: current
            artifact: $(tfFilesArtifactName)
          - script: |
              terraform init \
                  -backend-config="storage_account_name=$(tfStateStorageAccountName)" \
                  -backend-config="container_name=$(tfStateStorageContainerName)"
              terraform apply \
                  -auto-approve \
                  -var resource_group_name=$(resourceGroupName) \
                  -var location=$(location)
              terraform output resource_group_id
            workingDirectory: $(pipeline.workspace)/$(tfFilesArtifactName)
            displayName: 'Terraform apply'
            env:
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
                ARM_CLIENT_ID: $(clientId)
                ARM_CLIENT_SECRET: $(clientSecret)
                ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
