trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md
    - azure-pipeline.png

variables:
  vmImage: 'ubuntu-16.04'
  terraformVersion: 0.12.7
  tfFilesArtifactName: 'tf-files'

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Prepare'
    displayName: 'Prepare'
    pool:
      vmImage: $(vmImage)
    steps:
    - publish: '$(system.defaultWorkingDirectory)/tf'
      artifact: $(tfFilesArtifactName)
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)
    - script: |
        terraform init -backend=false
        terraform validate
      workingDirectory: $(system.defaultWorkingDirectory)/tf
      displayName: 'Terraform validate'
- stage: 'Plan_development'
  displayName: 'Plan development'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - job: 'Plan'
    # for release, define 6 more variables: location, resourceGroupName, clientId, clientSecret, subscriptionId and tenantId in the pipeline definition UI
    displayName: 'Plan'
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - download: current
      artifact: $(tfFilesArtifactName)
    - script: |
        terraform init -backend-config="storage_account_name=$(tfStateStorageAccountName)"
        terraform plan -var resource_group_name=$(resourceGroupName) -var location=$(location)
      workingDirectory: $(pipeline.workspace)/$(tfFilesArtifactName)
      displayName: 'Terraform plan'
      env:
          ARM_TENANT_ID: $(tenantId)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
- stage: 'Apply_development'
  displayName: 'Apply development'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: 'Apply'
    # define 6 more variables: location, resourceGroupName, clientId, clientSecret, subscriptionId and tenantId in the pipeline definition UI
    displayName: 'Apply'
    pool:
      vmImage: $(vmImage)
    environment: "tf-development"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - download: current
            artifact: $(tfFilesArtifactName)
          - script: |
              terraform init -backend-config="storage_account_name=$(tfStateStorageAccountName)"
              terraform apply -auto-approve -var resource_group_name=$(resourceGroupName) -var location=$(location)
            workingDirectory: $(pipeline.workspace)/$(tfFilesArtifactName)
            displayName: 'Terraform apply'
            env:
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
                ARM_CLIENT_ID: $(clientId)
                ARM_CLIENT_SECRET: $(clientSecret)
                ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
