trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md
    - azure-pipeline.png
    
pr: none

variables:
  vmImage: 'ubuntu-16.04'
  terraformVersion: 0.12.20
  tfFilesArtifactName: 'tf-files'
  tfPlanArtifactName: 'tf-plan'

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Prepare'
    displayName: 'Prepare'
    pool:
      vmImage: $(vmImage)
    steps:
    - publish: '$(system.defaultWorkingDirectory)/tf'
      artifact: $(tfFilesArtifactName)
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)
    - script: |
        terraform -version
        terraform init \
            -backend=false
        terraform validate
      workingDirectory: $(system.defaultWorkingDirectory)/tf
      failOnStderr: true
      displayName: 'Terraform validate'
- stage: 'Plan_development'
  displayName: 'Plan development'
  variables:
    - group: tf-sp-group-dev
    - group: tf-state-group-dev
    - group: tf-deployment-group-dev
  jobs:
  - job: 'Plan'
    displayName: 'Plan'
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - download: current
      artifact: $(tfFilesArtifactName)
    - script: |
        terraform init \
            -backend-config="storage_account_name=$(tfStateStorageAccountName)" \
            -backend-config="container_name=$(tfStateStorageContainerName)"
        terraform plan \
            -var resource_group_name=$(resourceGroupName) \
            -var location=$(location) \
            -out=tf-plan
         ls -l
      workingDirectory: $(pipeline.workspace)/$(tfFilesArtifactName)
      failOnStderr: true
      displayName: 'Terraform plan'
      env:
          ARM_TENANT_ID: $(tenantId)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_CLIENT_ID: $(clientId)
          ARM_CLIENT_SECRET: $(clientSecret)
          ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
    - publish: '$(pipeline.workspace)/$(tfFilesArtifactName)'
      artifact: $(tfPlanArtifactName)
- stage: 'Apply_development'
  displayName: 'Apply development'
  variables:
    - group: tf-sp-group-dev
    - group: tf-state-group-dev
  jobs:
  - deployment: 'Apply'
    displayName: 'Apply'
    pool:
      vmImage: $(vmImage)
    environment: tf-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - download: current
            artifact: $(tfPlanArtifactName)
          - script: |
              ls -l
              chmod +x .terraform/plugins/linux_amd64/terraform-provider-azurerm_v1.*
              terraform apply tf-plan
              terraform output resource_group_id
            workingDirectory: $(pipeline.workspace)/$(tfPlanArtifactName)
            failOnStderr: true
            displayName: 'Terraform apply'
            env:
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
                ARM_CLIENT_ID: $(clientId)
                ARM_CLIENT_SECRET: $(clientSecret)
                ARM_ACCESS_KEY: $(tfStateStorageAccountAccessKey)
